#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dota2Simulator.SourceGenerators;

/// <summary>
/// Phase 10A Chunk D: 扫描 GameAutomation/Heroes/**/*Strategy.cs 文本 + emit PictureHeroPreloadHints 字典.
/// SSOT = Strategy.cs 文本内的 Dota2_Pictrue.X.Y 引用; SG 在编译期 regex 扫 + 按英雄(文件名 stem)聚合.
/// 输出 public static IReadOnlyDictionary&lt;heroName, manifestKey[]&gt; Hints, 调用方按需 Preload.
/// HeroLoopHost / SkillEngine / ItemEngine 集成留给用户后续按需 hook, 本 chunk 仅 emit.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PictureHeroPreloadGenerator : IIncrementalGenerator
{
    // 反向映射 (.cs 嵌套类名 → manifest 键前缀) 已移至 PictureCategoryMap.ClassNameToManifestPrefix (B1: 消双 dict 漂移)

    // regex: Dota2_Pictrue.<嵌套类>.<属性名>
    // \w 不含中文, 用字符类 [\w一-鿿] 覆盖中文标识符 (失败处理 §三条)
    private static readonly Regex DotaPictrueRegex = new(
        @"Dota2_Pictrue\.([\w一-鿿]+)\.([\w一-鿿]+)",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 收集 GameAutomation/Heroes/**/*Strategy.cs 路径 + 文本
        var strategyFiles = context.AdditionalTextsProvider
            .Where(static at =>
            {
                var p = at.Path.Replace('\\', '/');
                if (p.IndexOf("/GameAutomation/Heroes/", StringComparison.OrdinalIgnoreCase) < 0) return false;
                // 用 Path.GetFileName 标准化, 避免目录名误命中
                var fileName = Path.GetFileName(p);
                return fileName.EndsWith("Strategy.cs", StringComparison.Ordinal);
            })
            .Select(static (at, ct) =>
            {
                var heroName = Path.GetFileNameWithoutExtension(at.Path);
                if (heroName.EndsWith("Strategy", StringComparison.Ordinal))
                    heroName = heroName.Substring(0, heroName.Length - "Strategy".Length);

                var text = at.GetText(ct)?.ToString() ?? string.Empty;
                var keys = new SortedSet<string>(StringComparer.Ordinal);
                foreach (Match m in DotaPictrueRegex.Matches(text))
                {
                    var className = m.Groups[1].Value;
                    var propertyName = m.Groups[2].Value;
                    if (!PictureCategoryMap.ClassNameToManifestPrefix.TryGetValue(className, out var prefix))
                        continue; // 未登记类名 (现状仅 6 类, 跳过未知)
                    keys.Add($"{prefix}.{propertyName}");
                }

                return (heroName, keys: keys.ToImmutableArray());
            })
            .Where(static t => t.keys.Length > 0) // 只 emit 实际引 Dota2_Pictrue 的 Strategy
            .Collect();

        context.RegisterSourceOutput(strategyFiles, static (spc, data) =>
        {
            var src = Emit(data);
            spc.AddSource("PictureHeroPreloadHints.g.cs", SourceText.From(src, Encoding.UTF8));
        });
    }

    private static string Emit(ImmutableArray<(string heroName, ImmutableArray<string> keys)> data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// SSOT: GameAutomation/Heroes/**/*Strategy.cs 文本; SG = PictureHeroPreloadGenerator.");
        sb.AppendLine("// 用法: PictureHeroPreloadHints.Hints[heroName] => manifest key 数组, 调用方按需 PreloadImagesAsync.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if DOTA2");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Dota2Simulator.Vision");
        sb.AppendLine("{");
        sb.AppendLine("    public static class PictureHeroPreloadHints");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static readonly IReadOnlyDictionary<string, string[]> Hints = new Dictionary<string, string[]>({data.Length})");
        sb.AppendLine("        {");

        foreach (var (hero, keys) in data.OrderBy(static x => x.heroName, StringComparer.Ordinal))
        {
            var keysLit = string.Join(", ", keys.Select(static k => $"\"{EscapeStringLiteral(k)}\""));
            sb.Append("            [\"").Append(EscapeStringLiteral(hero)).Append("\"] = new[] { ").Append(keysLit).AppendLine(" },");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#endif");

        return sb.ToString();
    }

    private static string EscapeStringLiteral(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
