#nullable enable
using Microsoft.CodeAnalysis;

namespace Dota2Simulator.SourceGenerators;

/// <summary>
/// Phase 10A Chunk A: Hello-world 注入, 验证 SG 激活链路.
/// 后续 chunk B/C 会替换 RegisterPostInitializationOutput 为真扫描 + SHA1 emit.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PictureManifestGenerator : IIncrementalGenerator
{
    private const string MarkerSource = """
        // <auto-generated />
        #nullable enable
        namespace Dota2Simulator.Games.Dota2
        {
            internal static class Dota2_PictrueGenMarker
            {
                internal const string Activated = "yes";
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("Dota2_PictrueGenerated.g.cs", MarkerSource));
    }
}
